media:
  input: assets/images/works
  output: /assets/images/works

content:

  # ==========================
  # WORKS COLLECTION
  # ==========================

  - name: works
    label: Works
    type: collection
    path: _works

    view:
      fields: [title, lang, date]

    fields:
      - name: title
        label: Title
        type: string

      - name: date
        label: Date
        type: date

      - name: excerpt
        label: Short description
        type: text

      - name: coverImage
        label: Cover image
        type: image

      - name: published
        label: Published
        type: boolean
        default: true

      - name: lang
        label: Language
        type: select
        options:
          values:
            - en
            - de
        default: en

      - name: page_id
        label: Page ID
        type: string

      - name: permalink
        label: Permalink
        type: string

      - name: meta_title
        label: Meta Title
        type: string

      - name: meta_description
        label: Meta Description
        type: text

      - name: body
        label: Content
        type: rich-text